# Generated by Django 5.1.2 on 2024-11-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('Class', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('Student_id', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checked_in', models.DateTimeField()),
                ('checked_out', models.DateTimeField(blank=True, null=True)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='BookTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('days_registered', models.PositiveIntegerField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('Book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
