# Generated by Django 5.1.2 on 2024-11-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktransaction',
            old_name='Book_id',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='booktransaction',
            old_name='Student_id',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='librarylog',
            old_name='Student_id',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_id',
            new_name='Student',
        ),
    ]
