# Generated by Django 5.1.2 on 2024-11-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_manager_options_alter_manager_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktransaction',
            old_name='Book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='booktransaction',
            old_name='Student',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='librarylog',
            old_name='Student',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Class',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student',
            new_name='student_id',
        ),
    ]
