# Generated by Django 5.1.2 on 2024-11-06 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_book_booktransaction_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 6, 18, 4, 36, 748479, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='librarylog',
            name='checked_in',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 18, 4, 36, 748479, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
