# Generated by Django 5.1.2 on 2024-11-06 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_token_alter_booktransaction_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='librarylog',
            name='checked_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
