# Generated by Django 5.1.2 on 2024-11-07 17:22

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=home.models.generate_random_string, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
