# Generated by Django 5.1.2 on 2024-11-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student', to_field='student_id'),
        ),
    ]
