# Generated by Django 5.1.2 on 2024-11-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_booktransaction_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student', to_field='student_id'),
        ),
    ]
