# Generated by Django 5.1.2 on 2024-11-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_librarylog_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarylog',
            old_name='student',
            new_name='student_id',
        ),
    ]
