# Generated by Django 5.1.2 on 2024-11-18 16:27

import time
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.BigIntegerField(default=int(time.time()), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.BigIntegerField(default=int(time.time()), editable=False),
        ),
    ]
