# Generated by Django 5.1.2 on 2024-11-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_category_created_at_alter_category_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='created_at',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='updated_at',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='updated_at',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='updated_at',
            field=models.BigIntegerField(editable=False),
        ),
    ]
