# Generated by Django 5.1.2 on 2024-11-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_book_created_at_alter_book_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='created_date',
        ),
    ]
