# Generated by Django 5.1.2 on 2024-11-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_token_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='borrow_date',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='return_date',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='librarylog',
            name='checked_in',
            field=models.BigIntegerField(default=1732041859),
        ),
        migrations.AlterField(
            model_name='librarylog',
            name='checked_out',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
