# Generated by Django 5.1.2 on 2024-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_delete_token_alter_book_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylog',
            name='checked_in',
            field=models.BigIntegerField(default=1732042365),
        ),
    ]
