# Generated by Django 5.1.2 on 2024-11-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_librarylog_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylog',
            name='checked_in',
            field=models.BigIntegerField(default=1732126910),
        ),
    ]
