# Generated by Django 5.1.2 on 2024-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_booktransaction_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylog',
            name='checked_in',
            field=models.BigIntegerField(default=1732127582),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.BigIntegerField(default=1732127582),
        ),
    ]
