# Generated by Django 5.1.2 on 2024-11-21 13:26

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_librarylog_checked_in_alter_student_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylog',
            name='checked_in',
            field=models.BigIntegerField(default=1732195616),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.BigIntegerField(default=1732195616),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=home.models.generate_random_string, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
