# Generated by Django 5.1.2 on 2024-11-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_librarylog_checked_in_alter_student_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylog',
            name='checked_in',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.BigIntegerField(default=1732205620),
        ),
    ]
