# Generated by Django 5.1.2 on 2024-11-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_librarylog_checked_in_alter_student_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.BigIntegerField(default=1732205841),
        ),
    ]
